/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlns.ui;

import com.qlns.entity.ClassQLChamCong;
import com.qlns.utils.JDBC;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author tuann
 */
public class QLChamCong extends javax.swing.JFrame {
    
//    private int row;
//    public ChamCongJFrame qlchamcong;

    /**
     * Creates new form QLChamCong
     */
    public QLChamCong() {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
    }
    List<ClassQLChamCong> list = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel(new String[]{"Mã nhân viên", "Họ và tên", "Ngày giờ vào ca", "Ngày giờ ra ca"}, 0);

    private void loadData() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        tblChamCong.setModel(model);
        String sql = "select chamcong.MaNV, NhanVien.HoVaTen, chamcong.NgayGioVaoCong, chamcong.NgayGioRaCong\n"
                + "from chamcong \n"
                + "join NhanVien on chamcong.MaNV = NhanVien.MaNV";
        ResultSet rs = JDBC.query(sql);
        model.setRowCount(0);
        
        try {
            while (rs.next()) {

                String manv = rs.getString("MaNV");
                String hovaten = rs.getString("HoVaTen");
                String ngayGioVaoCa = rs.getString("NgayGioVaoCong");
                String ngayGioRaCa = rs.getString("NgayGioRaCong");
                
                ClassQLChamCong qlcc = new ClassQLChamCong(manv, hovaten, ngayGioVaoCa, ngayGioRaCa);
                list.add(qlcc);
                model.addRow(new Object[]{manv,hovaten, ngayGioVaoCa, ngayGioRaCa});
                
            }
            
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(QLChamCong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    
    private void xuatExcel(){
        try {
            //workbook đại diện cho file excel
            XSSFWorkbook workbook = new XSSFWorkbook();
            //sheet đại diện cho 1 trang tính
            XSSFSheet sheet = workbook.createSheet("Danhsachchamcong");
            //row đại diện cho 1 hàng
            XSSFRow row = null;
            //cell đại diện cho 1 ô
            Cell cell = null;
            
            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã NV");
            
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Họ và tên");
            
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Ngày giờ vào ca");
            
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Ngày giờ ra ca");
            
            
            for (int i =0; i < list.size(); i++) {
                row = sheet.createRow(4+i);
                
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue(list.get(i).getMaNV());
                
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(list.get(i).getHoVaTen());
                
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(list.get(i).getNgayGioVaoCa());
                
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(list.get(i).getNgayGioRaCa());
            }
            
            File file = new File("danhsachchamcong.xlsx");
            
            try {
                FileOutputStream fileOutput = new FileOutputStream(file);
                workbook.write(fileOutput);
                fileOutput.close();
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(this, "Xuất file thành công");
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        btnIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ CHẤM CÔNG");

        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblChamCong);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        btnIn.setText("Xuất File");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIn)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        xuatExcel();
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLChamCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLChamCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChamCong;
    // End of variables declaration//GEN-END:variables

}
